---
title: "Eurovision: All Results"
author: "mnaR99"
date: "13/7/2020"
output: html_document
---

```{r}
library(rvest)
library(tidyverse)
```

```{r}
evhtml <- read_html("https://eurovision.tv/countries")
```

```{r}
countries_url <- evhtml %>% 
  html_nodes(".h-full.outline-none") %>% 
  html_attr("href")
```

```{r}
get_country_data <- function(url){

  country <- read_html(url) %>% 
    html_nodes(".pl-10 h1") %>% 
    html_text(TRUE)
  
  read_html(url) %>% 
    html_table(fill = T) %>% 
    .[[1]] %>% 
    as_tibble() %>% 
    unite(c1, X1:X3, sep = "|") %>%
    mutate(c2 = str_detect(c1, "\\d{4}"), c3 = ifelse(c2, c1, NA)) %>% 
    fill(c3) %>%
    separate(c3, into = c("EV","contestant","song"), sep = "\\|") %>% 
    extract(EV, c("city", "year"), "(.*)\\s(\\d{4})$", convert = T) %>% 
    filter(ifelse(year < 2004, T, !c2)) %>% 
    mutate(c1 = ifelse(c2, "Final", c1),
           c1 = str_extract(c1, "^([^\\|]+)"),
           c1 = recode(c1, "Grand Final" = "Final")) %>%
    extract(X4, "place", "(\\d{1,2})[a-z]{2}$", remove = F) %>% 
    extract(X4, "points", "(\\d+) points", remove = F) %>% 
    transmute(year, city, country, contestant, song, event = c1, points, place)
}
```

```{r}
country_data <- map_df(countries_url, get_country_data)

all_results <- country_data %>% 
  mutate(across(points:place, as.numeric)) %>% 
  mutate(points = case_when(is.na(points) & between(year, 1957, 2019) ~ 0,
                            TRUE ~ points),
         event = factor(event, levels = c("First Semi-Final", "Second Semi-Final", "Semi-Final", "Final"))) %>% 
  arrange(year, event, -place)

write_csv(all_results, here::here("data","all_results.csv"))
```

