---
title: 'Eurovision: Event Information'
author: "mnaR99"
date: "12/7/2020"
output: html_document
---

```{r}
library(rvest)
library(tidyverse)
library(lubridate)
library(janitor)
```

```{r}
evhtml <- read_html("https://eurovision.tv/events")
```

```{r}
events_urls <- evhtml %>% 
  html_node("main") %>% 
  html_nodes("a") %>% 
  html_attr("href") %>% 
  str_subset("event/") %>% 
  .[-(1:2)]
```

```{r}
infobox <-
  events_urls %>% 
  map_df(
     ~ read_html(.x) %>% 
    html_nodes(".space-y-4 .font-bold") %>% 
    html_text(TRUE) %>% 
    matrix(ncol = 2, byrow = TRUE) %>% 
    as_tibble() %>%
    set_names(c("key","value")),
    .id = "event_id"
  )
```

```{r}
event_info <-
  infobox %>% 
  mutate(key = recode(key, "Grand Final" = "Final", "Semi-Final" = "SF0", "First Semi-Final" = "SF1", "Second Semi-Final" = "SF2")) %>% 
  spread(key, value) %>% 
  gather(round, date, "Final", "SF0", "SF1", "SF2") %>%
  filter(!is.na(date)) %>% 
  clean_names() %>% 
  mutate(
    across(2:5, ~ ifelse(. %in% c("","—"), NA_character_, .)),
    across(c(2,5,6), ~ str_replace(., " (and|&)", ",")),
    year = as.numeric(str_extract(date, "\\d{4}")),
    date = str_remove(date,", \\d{2}:.+$")
  ) %>% 
  select(10:1, -event_id) %>% 
  extract(venue_location, c("venue","city","country"), "^(.*[,]?), (.*), (.*)$") %>%
  mutate(date = dmy(date)) %>% 
  arrange(year, date) %>% 
  rename(host_country = country)
```

```{r}
write_csv(event_info, here::here("data","event_info.csv"))
```