---
title: "Eurovision Lyrics 2010-2020"
author: "mnaR99"
date: "12/7/2020"
output: html_document
---

```{r}
library(rvest)
library(tidyverse)
```

```{r}
evhtml <- read_html("https://eurovision.tv/events")

events_urls <- evhtml %>% 
  html_node("main") %>% 
  html_nodes("a") %>% 
  html_attr("href") %>% 
  str_subset("event/") %>% 
  .[2:12]
```

```{r}
get_event_lyrics <- function(eurl){
  
  participants <- eurl %>% 
    str_c("/participants") %>% 
    read_html() %>% 
    html_nodes(".h-full.outline-none") %>% 
    html_attr("href")
  
  get_infobox_participant <- function(url){
  
    participant <- read_html(url)
    
    name <- participant %>% 
      html_node(".pl-10 h1") %>% 
      html_text(T)
    
    language <- participant %>% 
      html_nodes(".space-x-4") %>% 
      html_nodes("button") %>% 
      html_text(TRUE)
    
    lyrics <- participant %>% 
      html_nodes(".whitespace-pre-line") %>% 
      html_text(TRUE)
    
    infobox <- participant %>% 
      html_node(".bg-gray-200 .space-y-4") %>% 
      html_children() %>% 
      html_children() %>% 
      html_text(trim = TRUE)
    
    infobox <- c("Contestant", name, infobox) %>%
      matrix(ncol = 2, byrow = T, dimnames = list(NULL, c("key","value"))) %>% 
      as_tibble() %>% 
      spread(key, value)
    
    tibble(infobox, language, lyrics)
  }
  
  map_df(participants, get_infobox_participant)
}
```

```{r}
eurovision_lyrics <- tibble(events_urls) %>% 
  mutate(participants_info = map(events_urls, get_event_lyrics))

write_rds(eurovision_lyrics, here::here("data","lyrics.rds"))
```

```{r}
eurovision_lyrics  <- read_rds(here::here("data","lyrics.rds"))
  
lyrics <- eurovision_lyrics %>% 
  unnest() %>% 
  janitor::clean_names() %>% 
  select(events_urls, country, contestant, song, composed_by, written_by, language, lyrics) %>%
  mutate(
    year = str_extract(events_urls, "\\d{4}"), .before = 1,
    language = na_if(language, ""),
    language = str_replace_all(language, "/",", ") %>% str_squish()
  )

write_csv(lyrics, here::here("data","lyrics.csv"))
```
