---
title: "Eurovision: Grand Final Results"
author: "mnaR99"
date: "12/7/2020"
output: html_document
---

```{r}
library(rvest)
library(tidyverse)
```

```{r}
evhtml <- read_html("https://eurovision.tv/events")
```

```{r}
events_urls <- evhtml %>% 
  html_node("main") %>% 
  html_nodes("a") %>% 
  html_attr("href") %>% 
  str_subset("event/") %>% 
  .[-(1:2)]
```

```{r}
grand_finals <- events_urls %>% 
  str_c(c(rep("/grand-final",16),rep("/final",48))) %>% 
  map(possibly(read_html, otherwise = NULL))
```

```{r}
get_scoreboard <- function(event){
  event_name <- event %>% 
    html_node("h1") %>% 
    html_text(trim = TRUE)
  
  city <- str_remove(event_name, "\\s\\d{4}$")
  
  year <- as.numeric(str_extract(event_name, "\\d{4}"))
  
  event %>% 
    html_table() %>% 
    .[[1]] %>% 
    mutate_all(as.character) %>% 
    janitor::clean_names() %>% 
    rename(running_order = r_o) %>% 
    mutate(year, city, .before = 1)
}
```

```{r}
scoreboards <- grand_finals %>% 
  map_df(get_scoreboard, .id = "url_index") %>% 
  as_tibble() %>% 
  mutate(across(c(4,8,9), parse_number),
         event_url = map_chr(url_index, ~events_urls[as.numeric(.x)]), 
         .after = 3) %>%
  mutate(points = case_when(is.na(points) & year > 1956 ~ 0,
                            TRUE ~ points)) %>% 
  select(-url_index)

write_csv(scoreboards, path = here::here("data","grand_final.csv"))
```
